api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import PersonViewSet, CategoryViewSet, LocationViewSet, EventViewSet, EventLocationViewSet

router_v1 = DefaultRouter()
router_v1.register('persons', PersonViewSet, basename='person')
router_v1.register('categories', CategoryViewSet, basename='category')
router_v1.register('locations', LocationViewSet, basename='location')
router_v1.register('events', EventViewSet, basename='event')
router_v1.register('event-locations', EventLocationViewSet, basename='event_location')

urlpatterns = [
    path('v1/', include(router_v1.urls), name='v1'),
]

events/urls.py
from django.urls import path

from .views import (
    index,
    event_detail,
    get_categories,
    get_locations,
    get_people,
    person_detail,
    CreateEvent,
    CreateEventLocation,
)

app_name = 'events'

urlpatterns = [
    path('create_event_location/', CreateEventLocation.as_view(), name='create_event_location'),
    path('create/', CreateEvent.as_view(), name='create_event'),
    path('people/<int:person_id>/', person_detail, name='person_detail'),
    path('people/', get_people, name='people'),
    path('locations/', get_locations, name='locations'),
    path('categories/', get_categories, name='categories'),
    path('<int:event_id>/', event_detail, name='event_detail'),
    path('', index, name='index'),
]

eventy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
    path('', include('events.urls'), name='events'),
]

events/models.py
from django.db.models import (
    Model,
    CharField,
    PositiveSmallIntegerField,
    ForeignKey,
    DateField,
    TimeField,
    ManyToManyField,
    CASCADE,
)


class Person(Model):
    first_name = CharField(max_length=100, verbose_name='Имя')
    last_name = CharField(max_length=100, verbose_name='Фамилия')
    description = CharField(max_length=500, verbose_name='Описание')

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Участник'
        verbose_name_plural = 'Участники'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Category(Model):
    name = CharField(max_length=100, verbose_name='Название')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Event(Model):
    name = CharField(max_length=100, verbose_name='Название')
    description = CharField(max_length=500, verbose_name='Описание')
    category = ForeignKey(Category, on_delete=CASCADE, verbose_name='Категория', related_name='events')
    participants = ManyToManyField(Person, verbose_name='Участники', related_name='events')

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'
        ordering = ['name']

    def __str__(self):
        return self.name


class Location(Model):
    name = CharField(max_length=100, verbose_name='Название')
    city = CharField(max_length=100, verbose_name='Город')
    address = CharField(max_length=500, verbose_name='Адрес')
    capacity = PositiveSmallIntegerField(verbose_name='Вместимость')

    class Meta:
        verbose_name = 'Место проведения'
        verbose_name_plural = 'Места проведения'

    def __str__(self):
        return f'{self.name} ({self.city})'


class EventLocation(Model):
    event = ForeignKey(Event, on_delete=CASCADE, verbose_name='Событие', related_name='places')
    location = ForeignKey(Location, on_delete=CASCADE, verbose_name='Место проведения', related_name='events')
    date = DateField(verbose_name='Дата')
    time = TimeField(verbose_name='Время')
    price = PositiveSmallIntegerField(verbose_name='Цена')

    class Meta:
        verbose_name = 'Место и время проведения'
        verbose_name_plural = 'Места и время проведения'

    def __str__(self):
        return f'{self.event} ({self.location})'

events/forms.py
from django import forms
from django.forms import ModelForm

from .models import EventLocation


class EventLocationForm(ModelForm):
    date = forms.DateField(widget=forms.SelectDateWidget, label='Дата')
    time = forms.TimeField(widget=forms.TimeInput, label='Время')

    class Meta:
        model = EventLocation
        fields = '__all__'

api/views.py
from rest_framework import viewsets

from events.models import Person, Category, Event, Location, EventLocation
from .serializers import (
    PersonSerializer,
    CategorySerializer,
    LocationSerializer,
    EventReadSerializer,
    EventWriteSerializer,
    EventLocationReadSerializer,
    EventLocationWriteSerializer,
)


class PersonViewSet(viewsets.ModelViewSet):
    queryset = Person.objects.all()
    serializer_class = PersonSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class LocationViewSet(viewsets.ModelViewSet):
    queryset = Location.objects.all()
    serializer_class = LocationSerializer


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()

    def get_serializer_class(self):
        if self.request.method in ['POST', 'PATCH', 'PUT']:
            return EventWriteSerializer
        return EventReadSerializer


class EventLocationViewSet(viewsets.ModelViewSet):
    queryset = EventLocation.objects.all()

    def get_serializer_class(self):
        if self.request.method in ['POST', 'PATCH', 'PUT']:
            return EventLocationWriteSerializer
        return EventLocationReadSerializer

events/views.py
from django.db.models import Count, Subquery, OuterRef
from django.forms import IntegerField
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .models import Event, Category, Person, Location, EventLocation
from .forms import EventLocationForm


def index(request):
    events = Event.objects.all()
    return render(request, 'events/index.html', {'events': events})


def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, 'events/event_detail.html', {'event': event})


def get_categories(request):
    categories = Category.objects.all()
    return render(request, 'events/categories.html', {'categories': categories})


def get_locations(request):
    locations = Location.objects.all()
    return render(request, 'events/locations.html', {'locations': locations})


def get_people(request):
    people = Person.objects.annotate(events_count=Count('events__places'))
    return render(request, 'events/people.html', {'people': people})


def person_detail(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    return render(
        request,
        'events/person_detail.html',
        {'person': person},
    )


class CreateEvent(CreateView):
    model = Event
    fields = ['name', 'description', 'category', 'participants']
    template_name = 'events/create_event.html'

    def get_success_url(self):
        return reverse_lazy('events:event_detail', kwargs={'event_id': self.object.id})

    def form_valid(self, form):
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class CreateEventLocation(CreateView):
    model = EventLocation
    template_name = 'events/create_event_location.html'
    form_class = EventLocationForm

    def get_success_url(self):
        return reverse_lazy('events:event_detail', kwargs={'event_id': self.object.event_id})

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% bootstrap_css %}
</head>
<body>
    {% include 'include/header.html' %}
    <h1>
        {% block header %}
        {% endblock %}
    </h1>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% include 'include/footer.html' %}
</body>
</html>

templates/events/categories.html
{% extends 'base.html' %}

{% block title %}
    Категории
{% endblock %}

{% block header %}
    Категории
{% endblock %}

{% block content %}
    <ul>
        {% for category in categories %}
            <li><a href="">{{ category.name }}</a></li> (КОЛИЧЕСТВО СОБЫТИЙ)
        {% endfor %}
    </ul>

{% endblock %}

templates/events/create_event.html
{% extends 'base.html' %}

{% block title %}
    Добавить событие
{% endblock %}

{% block header %}
    Добавить событие
{% endblock %}

{% block content %}
    <form action="{% url 'events:create_event' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

templates/events/create_event_location.html
{% extends 'base.html' %}

{% block title %}
    Привязать событие к месту
{% endblock %}

{% block header %}
    Привязать событие к месту
{% endblock %}

{% block content %}
    <form action="{% url 'events:create_event_location' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
{% endblock %}

templates/events/event_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ event.name }}
{% endblock %}

{% block header %}
    {{ event.name }}
{% endblock %}

{% block content %}
    <article>
        <h2>{{ event.description }}</h2>
        <h4>Участники</h4>
        <ul>
            {% for participant in event.participants.all %}
                <li>{{ participant.full_name }}</li>
            {% endfor %}
        </ul>
        <h4>Даты и места проведения</h4>
        <ul>
            {% for place in event.places.all %}
                <div>
                    <h5>
                        {{ place.date }} - {{ place.time }}. Цена: {{ place.price }} руб. <a href="">Купить билет</a>
                    </h5>
                    <p>
                        Город: {{ place.location.city }}<br>
                        Адрес: {{ place.location.address }}<br>
                        Площадка: {{ place.location.name }}
                    </p>
                    <p>
                        Мест всего: {{ place.location.capacity }}<br>
                        Мест свободно: В РАЗРАБОТКЕ
                    </p>
                </div>
                <hr>
            {% endfor %}
        </ul>
        <a href="{% url 'events:create_event_location' %}">Добавить новое место</a>
    </article>
{% endblock %}

templates/events/index.html
{% extends 'base.html' %}

{% block title %}
    Eventy
{% endblock %}

{% block header %}
    Eventy
{% endblock %}

{% block content %}
    {% for event in events %}
        <article>
            <h2>{{ event.name }}</h2>
            <p>{{ event.description }}</p>
            <p><a href="{% url 'events:event_detail' event.id %}">подробнее</a></p>
        </article>
    {% endfor %}
{% endblock %}

templates/events/locations.html
{% extends 'base.html' %}

{% block title %}
    Локации
{% endblock %}

{% block header %}
    Локации
{% endblock %}

{% block content %}
    <ul>
        {% for location in locations %}
            <li><a href="">{{ location.name }}</a> (Всего событий: {{ location.events.count }})</li>
        {% endfor %}
    </ul>

{% endblock %}

templates/events/people.html
{% extends 'base.html' %}

{% block title %}
    Участники
{% endblock %}

{% block header %}
    Участники
{% endblock %}

{% block content %}
    <ul>
        {% for person in people %}
            <li><a href="{% url 'events:person_detail' person.id %}">{{ person.full_name }}</a>
                (Всего событий: {{ person.events.count }},
                количество возможных дат: {{ person.events_count }})</li>
        {% endfor %}
    </ul>

{% endblock %}

templates/events/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ person.full_name }}
{% endblock %}

{% block header %}
    {{ person.full_name }}
{% endblock %}

{% block content %}
    <article>
        <h2>{{ person.description }}</h2>
        <h4>Даты и места проведения</h4>
        <ul>
            {% for event in person.events.all %}
                <h3>
                {{ event.name }}
                </h3>
                {% for place in event.places.all %}
                    <div>
                        <h5>
                            {{ place.date }} - {{ place.time }}. Цена: {{ place.price }} руб. <a href="">Купить билет</a>
                        </h5>
                        <p>
                            Город: {{ place.location.city }}<br>
                            Адрес: {{ place.location.address }}<br>
                            Площадка: {{ place.location.name }}
                        </p>
                        <p>
                            Мест всего: {{ place.location.capacity }}<br>
                            Мест свободно: В РАЗРАБОТКЕ
                        </p>
                    </div>
                    <hr>
                {% endfor %}
            {% endfor %}

    </article>
{% endblock %}

templates/include/footer.html
<footer class="border-top text-center py-3">
  <p>© Eventy 2024</p>
</footer>

templates/include/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'events:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Eventy
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'events:categories' %} text-white {% endif %}" href="{% url 'events:categories' %}">
              Категории
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'events:locations' %} text-white {% endif %}" href="{% url 'events:locations' %}">
              Локации
            </a>
          </li>
            <li class="nav-item">
            <a class="nav-link {% if view_name == 'events:people' %} text-white {% endif %}" href="{% url 'events:people' %}">
              Участники
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'events:create_event' %}">Добавить событие</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'events:index' %}">Добавить событие в город</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'events:index' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'events:index' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'events:index' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

templates/include/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}